import { describe, expect, it } from 'vitest';
import { normalized, percent, weightedChoice } from '../src/core/probability';
import { DEFAULT_CONFIG, DIFFICULTIES, drawDifficulty, drawQuestion, GROUPS, MAPPING, validateConfig } from '../src/core/config';
import { bonusScore, tossupScore } from '../src/core/scoring';
import { canResume, gameReducer, newGame } from '../src/core/game';
import { parseBonuses, parseRuling, parseTossups, plainText, safeHTML } from '../src/api/parser';
import { preprocessSpeech, reached, speechSegments, timeline, tokenize } from '../src/reader/text';
import { aggregate, quarter, statistics } from '../src/stats/metrics';
import { patterns } from '../src/stats/patterns';
import type { Buzz, Config, GameState, Session } from '../src/core/types';
import { bonus, tossup } from './fixtures';
const c = (): Config => structuredClone(DEFAULT_CONFIG);
const draw = { group: 'Science & Math' as const, category: 'Science', difficulty: 3 as const };
function reading(config = c()) { return gameReducer(newGame(config), { type: 'LOAD', question: tossup, draw, generation: 1 }); }
function ruled(s: GameState, directive: 'accept' | 'reject', tokens = 2) { s = gameReducer(s, { type: 'BUZZ', tokens, elapsedMs: 500 }); s = gameReducer(s, { type: 'CHECK' }); return gameReducer(s, { type: 'RULING', ruling: { directive }, answer: 'water' }); }
describe('probability and configuration', () => {
  it('normalizes relative decimals, zero and huge weights without overflow', () => { const opts = [2, 6, 2, 0].map((weight, value) => ({ value, weight })); normalized(opts).forEach((o, i) => expect(o.weight).toBeCloseTo([.2, .6, .2, 0][i])); expect(normalized(opts.map(o => ({ ...o, weight: o.weight * 10 })))).toEqual(normalized(opts)); expect(normalized([{ value: 1, weight: 1e308 }, { value: 2, weight: 1e308 }]).map(o => o.weight)).toEqual([.5, .5]); expect(weightedChoice([{ value: 0, weight: 0 }, { value: 1, weight: .2 }], () => 0)).toBe(1); });
  it('rejects negative, NaN, infinity, all-zero and bad RNG', () => { for (const n of [-1, NaN, Infinity, 0]) expect(() => weightedChoice([{ value: 1, weight: n }])).toThrow(); expect(() => weightedChoice([{ value: 1, weight: 1 }], () => 1)).toThrow(); expect(percent({ x: 0 }, 'x')).toBe(0); });
  it('produces approximate independent probability over seeded large samples', () => { let seed = 5; const rng = () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 2 ** 32; }; let a = 0; for (let i = 0; i < 20000; i++) if (weightedChoice([{ value: 'a', weight: 2 }, { value: 'b', weight: 6 }], rng) === 'a') a++; expect(a / 20000).toBeGreaterThan(.23); expect(a / 20000).toBeLessThan(.27); });
  it('uses all nine groups, excludes unwanted categories, splits philosophy/religion equally', () => { expect(GROUPS).toHaveLength(9); expect(MAPPING['Science & Math']).toEqual(['Science']); expect(MAPPING['Pop Culture & Sports']).toEqual(['Pop Culture']); const cats = Object.values(MAPPING).flat(); for (const unwanted of ['Miscellaneous', 'Current Events', 'Other Academic']) expect(cats).not.toContain(unwanted); const cfg = c(); cfg.categories = Object.fromEntries(GROUPS.map(g => [g, g === 'Philosophy & Theology' ? 1 : 0])) as Config['categories']; expect(drawQuestion(cfg, () => 0).category).toBe('Philosophy'); expect(drawQuestion(cfg, () => .99).category).toBe('Religion'); });
  it('only draws enabled high-school difficulties and validates user input', () => { expect(DIFFICULTIES).toEqual([2, 3, 4]); for (let i = 0; i < 100; i++) expect(drawDifficulty(c())).toBe(3); const cfg = c(); cfg.count = 0; cfg.difficulties = { 2: 0, 3: 0, 4: 0 }; cfg.categories.History = -1; cfg.scores.ten = NaN; expect(validateConfig(cfg)).toHaveLength(4); expect(validateConfig(c())).toEqual([]); });
});
describe('scoring', () => {
  const buzz: Buzz = { words: 2, total: 12, elapsedMs: 300, inPower: true, ended: false };
  it('scores power, ten, neg and end miss under configurable rules', () => { expect(tossupScore(true, buzz, c())).toEqual({ result: 'power', points: 15 }); expect(tossupScore(true, { ...buzz, inPower: false }, c()).points).toBe(10); expect(tossupScore(false, buzz, c()).points).toBe(-5); expect(tossupScore(false, { ...buzz, ended: true }, c()).points).toBe(0); expect(tossupScore(true, buzz, { ...c(), powers: false })).toEqual({ result: 'ten', points: 10 }); expect(tossupScore(false, buzz, { ...c(), negs: false })).toEqual({ result: 'incorrect_no_penalty', points: 0 }); expect(tossupScore(true, buzz, { ...c(), scoring: false }).points).toBe(0); expect(tossupScore(true, buzz, { ...c(), scores: { ...c().scores, power: 20 } }).points).toBe(20); });
  it('uses actual bonus point values, fallback and disabled scoring', () => { expect(bonusScore(true, c(), 15)).toBe(15); expect(bonusScore(true, c())).toBe(10); expect(bonusScore(false, c(), 15)).toBe(0); expect(bonusScore(true, { ...c(), scoring: false }, 15)).toBe(0); });
});
describe('game reducer', () => {
  it('guards illegal transitions and stale loads', () => { const s = newGame(c()); expect(gameReducer(s, { type: 'CHECK' })).toBe(s); expect(gameReducer(s, { type: 'LOAD', question: tossup, draw, generation: 999 })).toBe(s); expect(gameReducer(s, { type: 'NEXT' })).toBe(s); });
  it('freezes reveal on buzz, prompts without answer exposure and accepts clarification', () => { let s = reading(); s = gameReducer(s, { type: 'PROGRESS', tokens: 2, elapsedMs: 500, ended: false }); s = gameReducer(s, { type: 'BUZZ', tokens: 2, elapsedMs: 500 }); const frozen = s; expect(gameReducer(s, { type: 'PROGRESS', tokens: 10, elapsedMs: 1000, ended: true })).toBe(frozen); s = gameReducer(s, { type: 'CHECK' }); s = gameReducer(s, { type: 'RULING', ruling: { directive: 'prompt', directedPrompt: 'Which liquid?' }, answer: 'liquid' }); expect(s.phase).toBe('PROMPTED'); expect(s.currentEvents).toHaveLength(0); s = gameReducer(s, { type: 'CHECK' }); s = gameReducer(s, { type: 'RULING', ruling: { directive: 'accept' }, answer: 'water' }); expect(s.session.attempts[0].events[0].points).toBe(15); });
  it('resumes after neg, locks out, completes reading, counts one tossup', () => { let s = ruled(reading(), 'reject'); expect(canResume(s)).toBe(true); s = gameReducer(s, { type: 'RESUME_NEG' }); expect(s.locked).toBe(true); expect(gameReducer(s, { type: 'BUZZ', tokens: 3, elapsedMs: 900 })).toBe(s); s = gameReducer(s, { type: 'PROGRESS', tokens: 12, elapsedMs: 3000, ended: true }); expect(s.phase).toBe('TOSSUP_RESOLVED'); expect(s.session.attempts).toHaveLength(1); expect(aggregate(s.session.attempts).n).toBe(1); });
  it('supports re-buzz with separate neg and conversion events', () => { let s = ruled(reading({ ...c(), rebuzz: true }), 'reject'); s = gameReducer(s, { type: 'RESUME_NEG' }); s = ruled(s, 'accept', 9); expect(aggregate(s.session.attempts)).toMatchObject({ tuh: 1, n: 1, ten: 1, points: 5 }); });
  it('prevents interrupts, respects exact marker and no-marker behavior', () => { const s = reading({ ...c(), interrupts: false }); expect(gameReducer(s, { type: 'BUZZ', tokens: 0, elapsedMs: 0 })).toBe(s); expect(ruled(reading(), 'accept', 7).currentEvents[0].result).toBe('power'); expect(ruled(reading(), 'accept', 8).currentEvents[0].result).toBe('ten'); const noMarker = gameReducer(newGame(c()), { type: 'LOAD', question: { ...tossup, question: 'No power here.' }, draw, generation: 1 }); expect(ruled(noMarker, 'accept', 1).currentEvents[0].result).toBe('ten'); });
  it('recalculates overrides, undo and give-up', () => { let s = ruled(reading(), 'reject'); s = gameReducer(s, { type: 'OVERRIDE', accepted: true }); expect(aggregate(s.session.attempts).points).toBe(15); expect(s.currentEvents[0].overridden).toBe(true); s = gameReducer(s, { type: 'UNDO' }); expect(s.phase).toBe('BUZZED'); expect(s.session.attempts).toHaveLength(0); s = gameReducer(s, { type: 'GIVE_UP' }); expect(s.session.attempts[0].noBuzz).toBe(true); expect(aggregate(s.session.attempts).points).toBe(0); });
  it('plays arbitrary bonus parts and finishes a one-tossup session', () => { let s = ruled(reading({ ...c(), count: 1, bonuses: true, mode: 'match' }), 'accept'); s = gameReducer(s, { type: 'REQUEST_BONUS' }); s = gameReducer(s, { type: 'BONUS_LOAD', question: { ...bonus, parts: bonus.parts.slice(0, 2), answers: bonus.answers.slice(0, 2), values: [5, 15] }, difficulty: 3, generation: 2 }); s = gameReducer(s, { type: 'BONUS_NEXT' }); for (let i = 0; i < 2; i++) { s = gameReducer(s, { type: 'BONUS_CHECK' }); s = gameReducer(s, { type: 'BONUS_RULING', ruling: { directive: 'accept' }, answer: 'test' }); s = gameReducer(s, { type: 'BONUS_NEXT' }); } expect(s.phase).toBe('BONUS_RESOLVED'); s = gameReducer(s, { type: 'NEXT' }); expect(s.phase).toBe('SESSION_COMPLETE'); expect(statistics([s.session])).toMatchObject({ p: 1, gp: 1, ppg: 15, ppb: 20, total: 35 }); });
});
describe('contract parsing and safe speech', () => {
  it('parses current tossup/bonus/ruling schemas and missing bonus answers defensively', () => { expect(parseTossups({ tossups: [tossup] })[0]._id).toBe(tossup._id); expect(parseBonuses({ bonuses: [bonus] })[0].parts).toHaveLength(3); expect(parseRuling({ directive: 'accept' }).directedPrompt).toBeNull(); expect(() => parseBonuses({ bonuses: [{ ...bonus, answers: [] }] })).toThrow(); expect(() => parseRuling({ directive: 'maybe' })).toThrow(); });
  it('sanitizes scripts, event handlers and unsafe markup', () => { const html = safeHTML('<img src=x onerror=alert(1)><script>alert(1)</script><b onclick="x()">Clue</b>'); expect(html).toBe('<b>Clue</b>'); expect(plainText('A &amp; B <i>C</i>')).toBe('A & B C'); });
  it('preserves canonical tokens and power boundary while preprocessing pronunciation', () => { const html = '<b>Dr. Gauss ("gows")</b> saw Henry VIII in 1905. (*) H2O equals 2 + 3.'; const t = tokenize(html); expect(t.fullDisplayText).toContain('("gows")'); const spoken = preprocessSpeech(html); expect(spoken).toContain('Doctor gows'); expect(spoken).toContain('Henry the eighth'); expect(spoken).toContain('H two O'); expect(spoken).not.toContain('(*)'); expect(t.powerBoundary).not.toBeNull(); expect(speechSegments(t).at(-1)?.end).toBe(t.tokens.length); });
  it('preserves adjacency across inline formatting and line-break word boundaries', () => { const t = tokenize('H<sub>2</sub>O is <i>liquid</i>.<br>Next clue. (*) End.'); expect(t.tokens.map(t => t.text)).toEqual(['H2O', 'is', 'liquid.', 'Next', 'clue.', 'End.']); expect(t.tokens[0].html).toBe('H<sub>2</sub>O'); expect(t.powerBoundary).toBe(5); expect(plainText('A<br>B')).toBe('A B'); });
  it('builds monotonic chunk timelines and progressive reveal', () => { const t = timeline([1, 2, 1], 1000); expect(t).toEqual([250, 750, 1000]); expect(reached(t, 749)).toBe(1); expect(reached(t, 1000)).toBe(3); });
});
describe('statistics and patterns', () => {
  it('excludes practice from default GP/PPG and has N/A bonus metrics', () => { const practice = ruled(reading(), 'accept').session; const match = { ...practice, id: 'match', config: { ...practice.config, mode: 'match' as const }, completedAt: '2026-10-03T13:00:00Z' }; expect(statistics([practice, match])).toMatchObject({ p: 2, tuh: 2, gp: 1, ppg: 15, ppb: null, correctBuzz: 2 / 11 * 100 }); expect(statistics([practice]).ppg).toBeNull(); });
  it('normalizes quarters to arbitrary round length', () => { expect([1, 6, 7, 12, 13, 18, 19, 24].map(n => quarter(n, 24))).toEqual([0, 0, 1, 1, 2, 2, 3, 3]); expect(quarter(5, 5)).toBe(3); expect(quarter(3, 10)).toBe(1); });
  it('groups categories/difficulties and refuses one-question pattern claims', () => { const s = ruled(reading(), 'accept').session; expect(patterns([s])[0]).toContain('at least 10'); const more: Session = { ...s, attempts: Array.from({ length: 12 }, (_, i) => ({ ...s.attempts[0], number: i + 1, draw: { ...draw, group: i < 6 ? 'History' : 'Science & Math' } })) }; expect(patterns([more])[0]).toContain('highest points per tossup'); });
});
