import { FixPronunciation } from './PronunciationEditor';
import { useEffect, useMemo, useRef, useState } from 'react';
import { canResume, converted, lastEvent } from '../core/game';
import type { Config, GameState, Session } from '../core/types';
import { statistics, buzzPercent } from '../stats/metrics';
import { useGame } from './useGame';
import { QuestionText } from './QuestionText';
export function Game({ config, recovery, onComplete, onExit }: { config: Config; recovery?: GameState; onComplete(s: Session): void; onExit(): void }) {
  const game = useGame(config, recovery); const { s, status, ready, dispatch } = game;
  const [answer, setAnswer] = useState(''); const input = useRef<HTMLInputElement>(null); const [reveal, setReveal] = useState(false);
  const answering = ['BUZZED', 'PROMPTED', 'BONUS_PART', 'BONUS_PROMPTED'].includes(s.phase); const checking = ['CHECKING', 'BONUS_CHECKING'].includes(s.phase);
  const bonus = s.phase.startsWith('BONUS') || s.phase === 'LOADING_BONUS'; const resolved = s.phase === 'TOSSUP_RESOLVED';
  const metrics = useMemo(() => statistics([s.session]), [s.session]); const event = lastEvent(s);
  useEffect(() => { if (answering) { setAnswer(''); input.current?.focus(); } }, [s.phase, s.part, answering]);
  useEffect(() => { setReveal(false); }, [s.number]);
  useEffect(() => { if (s.phase === 'SESSION_COMPLETE') onComplete(s.session); }, [s.phase, s.session, onComplete]);
  const controls = useRef({ s, game, answer }); controls.current = { s, game, answer };
  useEffect(() => {
    const keydown = (e: KeyboardEvent) => {
      if ((e.target as HTMLElement).closest('dialog')) return; const tag = (e.target as HTMLElement).tagName; if (['INPUT', 'TEXTAREA', 'SELECT'].includes(tag) || (e.target as HTMLElement).isContentEditable) return;
      const { s, game } = controls.current;
      if (e.code === 'Space' && s.phase === 'READING_TOSSUP') { e.preventDefault(); game.buzz(); }
      if (e.key === 'Enter' && !['BUTTON', 'SUMMARY'].includes(tag) && ['TOSSUP_RESOLVED', 'BONUS_LEADIN', 'BONUS_PART_RESOLVED', 'BONUS_RESOLVED'].includes(s.phase)) { e.preventDefault(); game.proceed(); }
    };
    window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown);
  }, []);
  const submit = (e: React.FormEvent) => { e.preventDefault(); void game.submit(answer); };
  const exit = () => { if (window.confirm('Leave this session? Your progress is saved so you can resume from setup.')) onExit(); };
  const nextLabel = canResume(s) ? 'Resume question' : converted(s) && config.bonuses ? 'Continue to bonus' : s.number >= config.count ? 'Finish session' : 'Next tossup';
  const showText = s.session.config.presentation !== 'audio' || status.includes('Reading · text');
  return <div className="game-page"><div className="game-top"><button className="text-button" onClick={exit}>← Leave session</button><span className="badge">{config.mode.toUpperCase()}</span></div><div className="game-heading"><div><span className="eyebrow">{bonus ? 'BONUS' : 'TOSSUP'} {s.number} / {config.count}</span><h1>{bonus ? 'Three more chances.' : 'Listen for your moment.'}</h1></div><div className="score-display"><span>SESSION SCORE</span><strong data-testid="score">{metrics.total}</strong><small>{metrics.p} / {metrics.ten} / {metrics.n}</small></div></div>
    <div className="round-track"><i style={{ width: `${(s.number - 1) / config.count * 100}%` }} /></div>
    {game.storageError && <p role="alert" className="error-message">{game.storageError}</p>}
    {s.phase === 'ERROR' ? <section className="panel error-panel"><span className="eyebrow">PLAYBACK PAUSED</span><h2>Let’s get you back in.</h2><p role="alert">{s.error}</p><button className="primary" onClick={() => dispatch({ type: 'RETRY' })}>Retry</button><p className="help">Your completed attempts are saved. History remains available offline.</p></section> : <section className="play-panel">
      {!bonus && s.question && <><div className="question-meta"><span>{s.draw?.group} <span className="meta-separator">/</span> Level {s.draw?.difficulty}</span><span>{s.locked ? 'LOCKED OUT' : s.paused ? 'PAUSED' : resolved ? 'RULING' : s.phase === 'READING_TOSSUP' ? s.ended ? 'READ COMPLETE' : 'READING' : 'BUZZED'}</span></div>
        {showText || (resolved && reveal) ? <QuestionText html={s.question.question} count={resolved && reveal ? undefined : s.tokens} /> : <div className="audio-only"><span aria-hidden="true">▂ ▅ ▇ ▃ ▆ ▂ ▅</span><h2>{resolved ? 'Question resolved' : 'Eyes off. Ears on.'}</h2><p>{Math.round(s.tokens / Math.max(1, game.totalTokens) * 100)}% heard</p></div>}
        {s.phase === 'READING_TOSSUP' && <><div className="reading-progress" aria-label="Question progress"><i style={{ width: `${s.tokens / Math.max(1, game.totalTokens) * 100}%` }} /></div><div className="play-controls"><button className="buzz-button" onClick={game.buzz} disabled={!ready || s.locked || (!config.interrupts && !s.ended)}>Buzz <kbd>Space</kbd></button><button onClick={game.pause} disabled={!ready || s.ended}>{s.paused ? 'Resume reader' : 'Pause'}</button><button onClick={game.giveUp}>Give up</button></div>{s.locked && <p className="help">You’re locked out after that incorrect interrupt. The reader will finish the tossup.</p>}{!config.interrupts && !s.ended && <p className="help">Interrupts are off. Buzz when the reader finishes.</p>}</>}
        {(answering || checking) && !bonus && <form onSubmit={submit} className="answer-form">{s.prompt && <p role="status" className="prompt-message">{s.prompt}</p>}<label htmlFor="answer">{s.phase === 'PROMPTED' ? 'Clarify your answer' : 'Your answer'}</label><div><input ref={input} id="answer" autoComplete="off" value={answer} disabled={checking} onChange={e => setAnswer(e.target.value)} placeholder="Type your answer…" /><button className="primary" disabled={checking || !answer.trim()}>{checking ? 'Checking…' : 'Submit'}</button></div><button type="button" className="text-button" disabled={checking} onClick={game.giveUp}>Give up</button></form>}
        {resolved && <div className="ruling-panel"><div className="ruling-heading"><span className={`result-label ${converted(s) ? 'correct' : ''}`}>{event ? ({ power: 'POWER', ten: 'CORRECT', neg: 'NEG', incorrect_no_penalty: 'INCORRECT', no_buzz: 'NO BUZZ' } as const)[event.result] : 'NO BUZZ'}</span><strong>{event ? `${event.points > 0 ? '+' : ''}${event.points}` : '0'} points</strong></div><p className="official-answer"><span>ANSWER</span> {s.question.answer_sanitized}</p><div className="ruling-details"><span>Your answer: {event?.userAnswer || '—'}</span><span>Buzz: {event ? `${buzzPercent(event.buzz.words, event.buzz.total).toFixed(0)}%` : '—'}</span><span>{s.question.subcategory} · Difficulty {s.question.difficulty}</span></div><div className="button-row"><button className="primary" onClick={game.proceed}>{nextLabel} →</button><FixPronunciation question={s.question.question} config={config}/><button onClick={() => setReveal(v => !v)}>{reveal ? 'Hide full question' : 'Reveal full question'}</button></div>{canResume(s) && <p className="help">Resume from your buzz point. {config.rebuzz ? 'You may buzz again.' : 'You will be locked out for the rest of this tossup.'}</p>}{event && <details className="override"><summary>Override ruling</summary><p className="help">Use when the automated judge made a mistake. Overrides are recorded.</p><div className="button-row"><button onClick={() => dispatch({ type: 'OVERRIDE', accepted: true })}>Mark correct</button><button onClick={() => dispatch({ type: 'OVERRIDE', accepted: false })}>Mark incorrect</button><button onClick={() => { setReveal(false); dispatch({ type: 'UNDO' }); }}>Undo last answer result</button></div>{event.overridden && <small>Manually overridden</small>}</details>}</div>}
      </>}
      {bonus && s.bonus && <><div className="question-meta"><span>Bonus · Level {s.bonusDifficulty}</span><span>{s.phase === 'BONUS_LEADIN' ? 'LEAD-IN' : `PART ${s.part + 1} / ${s.bonus.parts.length}`}</span></div>
        {s.phase === 'BONUS_LEADIN' ? <><QuestionText html={s.bonus.leadin} count={showText ? game.bonusTokens : 0} marker={false} /><div className="button-row"><button className="primary" onClick={game.proceed}>Begin bonus →</button></div></> : s.phase === 'BONUS_RESOLVED' ? <div className="ruling-panel"><h2>Bonus complete.</h2><p className="bonus-score">{s.bonusParts.reduce((sum, p) => sum + p.points, 0)} points</p><p>{s.bonusParts.filter(p => p.correct).length} / {s.bonus.parts.length} parts correct</p><button className="primary" onClick={game.proceed}>{s.number >= config.count ? 'Finish session' : 'Next tossup'} →</button></div> : <>
          {showText || s.phase === 'BONUS_PART_RESOLVED' ? <QuestionText html={s.bonus.parts[s.part]} count={s.phase === 'BONUS_PART_RESOLVED' ? undefined : game.bonusTokens} marker={false} /> : <div className="audio-only"><h2>Listen to part {s.part + 1}.</h2></div>}
          {s.phase === 'BONUS_PART_RESOLVED' ? <div className="ruling-panel"><div className="ruling-heading"><span className="result-label">{s.bonusParts.at(-1)?.correct ? 'CORRECT' : 'INCORRECT'}</span><strong>+{s.bonusParts.at(-1)?.points} points</strong></div><p className="official-answer"><span>ANSWER</span> {s.bonus.answers_sanitized[s.part]}</p><p>Your answer: {s.bonusParts.at(-1)?.userAnswer || '—'}</p><button className="primary" onClick={game.proceed}>{s.part + 1 >= s.bonus.parts.length ? 'Finish bonus' : 'Next part'} →</button><FixPronunciation question={s.bonus.parts[s.part]} config={config}/><details className="override"><summary>Override ruling</summary><div className="button-row"><button onClick={() => dispatch({ type: 'BONUS_OVERRIDE', correct: true })}>Mark correct</button><button onClick={() => dispatch({ type: 'BONUS_OVERRIDE', correct: false })}>Mark incorrect</button></div></details></div> : <form onSubmit={submit} className="answer-form">{s.prompt && <p role="status" className="prompt-message">{s.prompt}</p>}<label htmlFor="bonus-answer">{s.phase === 'BONUS_PROMPTED' ? 'Clarify your answer' : 'Your answer'}</label><div><input ref={input} id="bonus-answer" autoComplete="off" value={answer} onChange={e => setAnswer(e.target.value)} disabled={checking} /><button className="primary" disabled={checking || !answer.trim()}>{checking ? 'Checking…' : 'Submit'}</button></div><button className="text-button" type="button" disabled={checking} onClick={game.skipBonusPart}>Give up part</button><small>{game.bonusEnded ? 'Reader finished.' : 'You may answer when ready.'}</small></form>}
        </>}
      </>}
      {['LOADING_TOSSUP', 'LOADING_BONUS'].includes(s.phase) && <div className="loading-state"><span className="loading-dot"/><h2>{status}</h2><p className="help">Small batches. Fresh questions. No database download.</p></div>}
      <div className="reader-status" role="status"><span className="status-dot"/> {status}{!ready && s.question && s.phase === 'READING_TOSSUP' && config.presentation !== 'text' && <button className="text-button" onClick={game.switchReader}>Use System Voice now</button>}</div>
    </section>}
    <div className="game-footer"><span><kbd>Space</kbd> Buzz · <kbd>Enter</kbd> Submit / Continue</span><span>Solo play · no opponent</span></div>
  </div>;
}
