import { useMemo, useState } from 'react';
import type { Session } from '../core/types';
import { statistics } from '../stats/metrics';
import { Results } from './Results';
export function History({ sessions, onOpen, onDelete, onNew }: { sessions: Session[]; onOpen(s: Session): void; onDelete(id: string): Promise<void>; onNew(): void }) {
  const [filter, setFilter] = useState('all'); const [custom, setCustom] = useState<string[]>([]); const [tab, setTab] = useState<'history' | 'analytics'>('history');
  const filtered = useMemo(() => { const sorted = [...sessions].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); if (filter === 'custom') return sorted.filter(s => custom.includes(s.id)); if (filter === 'practice' || filter === 'match') return sorted.filter(s => s.config.mode === filter); if (filter.startsWith('last')) return sorted.filter(s => s.config.mode === 'match' && s.completedAt).slice(0, Number(filter.slice(4))); return sorted; }, [sessions, filter, custom]);
  return <><div className="history-intro"><span className="eyebrow">SAVED ON THIS DEVICE</span><h1>Your practice, over time.</h1><p>Return to a round. Find a pattern. Take the next step.</p></div><div className="history-toolbar"><div className="tabs"><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>Session history</button><button className={tab === 'analytics' ? 'active' : ''} onClick={() => setTab('analytics')}>Cumulative statistics</button></div><label>Show<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All Time</option><option value="last5">Last 5 Matches</option><option value="last10">Last 10 Matches</option><option value="last25">Last 25 Matches</option><option value="practice">Practice Only</option><option value="match">Match Only</option><option value="custom">Custom Sessions</option></select></label></div>{filter === 'custom' && <section className="panel custom-sessions">{sessions.map(s => <label key={s.id}><input type="checkbox" checked={custom.includes(s.id)} onChange={e => setCustom(old => e.target.checked ? [...old, s.id] : old.filter(id => id !== s.id))}/>{new Date(s.createdAt).toLocaleString()} · {s.config.mode}</label>)}</section>}
    {tab === 'analytics' ? <Results sessions={filtered} onNew={onNew}/> : <section className="panel history-list">{filtered.length ? filtered.map(s => { const stats = statistics([s]); return <article key={s.id}><div><span className="badge">{s.config.mode.toUpperCase()} {s.completedAt ? '' : '· IN PROGRESS'}</span><h3>{new Date(s.createdAt).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</h3><p>{s.attempts.length}/{s.config.count} tossups · {stats.p}/{stats.ten}/{stats.n} · TU {stats.points} pts{s.config.bonuses ? ` · Bonus ${stats.bonusPoints} pts · PPB ${stats.ppb?.toFixed(1) ?? 'N/A'}` : ''}</p></div><div className="history-score"><strong>{stats.total}</strong><small>Total score</small></div><div className="button-row"><button onClick={() => onOpen(s)}>View results →</button><button className="danger-text" aria-label={`Delete session ${s.id}`} onClick={() => { if (window.confirm('Permanently delete this session and its attempts? Seen question IDs will remain.')) void onDelete(s.id); }}>Delete</button></div></article>; }) : <div className="empty-state"><h2>A fresh start.</h2><p>Your saved sessions will appear here.</p><button className="primary" onClick={onNew}>Start a session ↗</button></div>}</section>}</>;
}
