import { useCallback, useEffect, useState } from 'react';
import type { Config } from '../core/types';
import { db } from '../data/db';
import { exportData, importData } from '../data/transfer';
import { PRONUNCIATIONS, type PersonalPronunciation } from '../data/pronunciations';
import { PronunciationEditor } from './PronunciationEditor';
export function Settings({ config, onImported }: { config: Config; onImported(): Promise<void> }) {
  const [entries, setEntries] = useState<PersonalPronunciation[]>([]); const [editor, setEditor] = useState<PersonalPronunciation | 'new'>(); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => setEntries(await db.pronunciations.orderBy('canonical').toArray()), []);
  useEffect(() => { void refresh().catch(e => setMessage(String(e))); }, [refresh]);
  const download = async () => { try { const text = await exportData(); const url = URL.createObjectURL(new Blob([text], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `cadence-data-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setMessage('Data exported. Keep this file to move your practice history.'); } catch (e) { setMessage(String(e)); } };
  return <div className="settings-page"><span className="eyebrow">YOUR PRACTICE ROOM</span><h1>Settings</h1><section className="panel"><div className="section-title"><h2>Pronunciation Dictionary</h2><button onClick={() => setEditor('new')}>Add correction</button></div><p className="help">Your corrections take priority over the built-in dictionary, then writer pronunciation guides. Changes apply the next time a question is read.</p>{entries.length ? <div className="dictionary-list">{entries.map(e => <div key={e.id}><span><strong>{e.canonical}</strong><small>{e.spoken}{e.caseSensitive ? ' · Exact case' : ''}</small></span><button aria-label={`Edit ${e.canonical}`} onClick={() => setEditor(e)}>Edit</button><button aria-label={`Delete ${e.canonical}`} onClick={() => void db.pronunciations.delete(e.id).then(refresh).catch(e => setMessage(String(e)))}>Delete</button></div>)}</div> : <p>No personal corrections yet. You can also fix pronunciation after a question or from its review.</p>}<details><summary>Built-in quiz bowl dictionary ({PRONUNCIATIONS.length})</summary>{PRONUNCIATIONS.map(e => <p key={e.canonical}><strong>{e.canonical}</strong> → {e.spoken}</p>)}</details></section><section className="panel"><h2>Move your data</h2><p>Export session history, presets, pronunciation corrections, settings and seen-question IDs. No account is needed.</p><p className="help">Import merges history and presets, keeping existing records with the same ID. Matching pronunciation corrections and preferences are replaced by the imported values. An unfinished game’s recovery checkpoint stays on its original device. Import is limited to validated Cadence version 1 JSON, up to 40 MB.</p><div className="button-row"><button disabled={busy} onClick={() => void download()}>Export Data</button><label className="import-button">Import Data<input type="file" accept=".json,application/json" disabled={busy} onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; if (file.size > 40 * 1024 * 1024) { setMessage('Choose a backup under 40 MB.'); return; } setBusy(true); void file.text().then(importData).then(async b => { await refresh(); await onImported(); setMessage(`Imported ${b.sessions.length} sessions, ${b.presets.length} presets and ${b.pronunciations.length} corrections. Duplicate history was kept.`); }).catch(e => setMessage(String(e))).finally(() => setBusy(false)); }}/></label></div><p role="status">{message}</p></section>{editor && <PronunciationEditor initial={editor === 'new' ? undefined : editor} config={config} onClose={() => setEditor(undefined)} onSaved={() => void refresh()}/>}</div>;
}
