import { useEffect, useState } from 'react';
import { BUILTINS, DEFAULT_CONFIG, DIFFICULTIES, GROUPS, IS_A, modePreset, validateConfig } from '../core/config';
import { percent } from '../core/probability';
import type { Config, Group } from '../core/types';
import { clearAll, db, saveSetting, type Preset } from '../data/db';
import { KOKORO_VOICES } from '../reader/kokoro';
import { SystemEngine } from '../reader/system';
import type { Voice } from '../reader/playback';
export function Toggle({ label, value, onChange, note }: { label: string; value: boolean; onChange(v: boolean): void; note?: string }) { return <label className="toggle-row"><span>{label}{note && <small>{note}</small>}</span><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} /><span className="switch" aria-hidden="true">{value ? 'On' : 'Off'}</span></label>; }
export function Setup({ initial, onStart, onClear, onChange }: { initial: Config; onStart(c: Config): void; onClear(): void; onChange?(c: Config): void }) {
  const [c, setC] = useState<Config>(structuredClone(initial)); const [presets, setPresets] = useState<Preset[]>([]); const [selected, setSelected] = useState(''); const [voices, setVoices] = useState<Voice[]>([]); const [message, setMessage] = useState('');
  const errors = validateConfig(c); const update = <K extends keyof Config>(key: K, value: Config[K]) => setC(old => ({ ...old, [key]: value }));
  useEffect(() => { void db.presets.toArray().then(setPresets); const system = new SystemEngine(); const refresh = () => { void system.listVoices().then(setVoices); }; refresh(); if ('speechSynthesis' in window) speechSynthesis.addEventListener('voiceschanged', refresh); return () => { if ('speechSynthesis' in window) speechSynthesis.removeEventListener('voiceschanged', refresh); }; }, []);
  useEffect(() => { if (!validateConfig(c).length) { onChange?.(c); void saveSetting('config', c).catch(() => setMessage('Could not save settings in this browser.')); } }, [c, onChange]);
  const savePreset = async () => { const name = window.prompt('Name this preset', 'My practice'); if (!name?.trim()) return; const p = { id: crypto.randomUUID(), name: name.trim(), config: structuredClone(c) }; await db.presets.put(p); setPresets(await db.presets.toArray()); setSelected(p.id); };
  const rename = async () => { const p = presets.find(p => p.id === selected); if (!p) return; const name = window.prompt('Rename preset', p.name); if (!name?.trim()) return; await db.presets.put({ ...p, name: name.trim() }); setPresets(await db.presets.toArray()); };
  const remove = async () => { if (!window.confirm('Delete this saved preset?')) return; await db.presets.delete(selected); setSelected(''); setPresets(await db.presets.toArray()); };
  const allVoices = c.engine === 'system' ? voices : [...KOKORO_VOICES, ...(c.engine === 'auto' ? voices : [])];
  return <div className="setup"><div className="page-intro"><span className="eyebrow">YOUR DAILY QUIZ BOWL REP</span><h1>Make every clue count.</h1><p>A focused practice room. Your distribution, your pace, your progress.</p></div>
    <div className="setup-layout"><div className="setup-main">
      <section className="panel"><div className="section-title"><span className="section-number">01</span><h2>The session</h2></div><div className="mode-options">{(['practice', 'match'] as const).map(mode => <button key={mode} className={`mode-option ${c.mode === mode ? 'selected' : ''}`} onClick={() => setC(modePreset(c, mode))} aria-pressed={c.mode === mode}><strong>{mode === 'practice' ? 'Practice' : 'Match'}</strong><span>{mode === 'practice' ? 'Build knowledge, one clue at a time.' : 'Play a full solo round with bonuses.'}</span></button>)}</div>
        <div className="session-options"><div><label htmlFor="count">Tossups in this session</label><div className="count-options">{[5, 10, 20, 24].map(n => <button key={n} onClick={() => update('count', n)} className={c.count === n ? 'active' : ''}>{n}</button>)}<input id="count" aria-label="Custom tossup count" type="number" min="1" max="500" step="1" value={Number.isFinite(c.count) ? c.count : ''} onChange={e => update('count', e.target.valueAsNumber)} /></div></div><Toggle label="Bonuses" note="After a correct tossup" value={c.bonuses} onChange={v => update('bonuses', v)} /></div>
      </section>
      <section className="panel"><div className="section-title"><span className="section-number">02</span><h2>Your question mix</h2><span className="badge">PROBABILITIES, NOT QUOTAS</span></div><div className="preset-row"><label htmlFor="categoryPreset">Distribution preset</label><select id="categoryPreset" value={JSON.stringify(c.categories) === JSON.stringify(IS_A) ? 'isa' : Object.values(c.categories).every(w => w === 1) ? 'equal' : 'custom'} onChange={e => { if (e.target.value !== 'custom') update('categories', e.target.value === 'isa' ? { ...IS_A } : Object.fromEntries(GROUPS.map(g => [g, 1])) as Record<Group, number>); }}><option value="isa">IS-A Academic</option><option value="equal">Equal Categories</option><option value="custom">Custom</option></select></div>
        <div className="weight-header"><span>Category</span><span>Weight</span><span>Probability</span></div>{GROUPS.map((g, i) => <div className="weight-row" key={g}><label htmlFor={`weight-${i}`}><span className={`category-dot dot-${i}`} />{g}</label><input id={`weight-${i}`} aria-label={`${g} weight`} type="number" min="0" step="any" value={Number.isFinite(c.categories[g]) ? c.categories[g] : ''} onChange={e => update('categories', { ...c.categories, [g]: e.target.valueAsNumber })} /><div className="probability"><span>{percent(c.categories, g).toFixed(1)}%</span><div className="mini-bar"><i style={{ width: `${percent(c.categories, g)}%` }} /></div></div></div>)}
        <p className="help">Each tossup is an independent random draw. Short rounds can vary substantially from this mix.</p>
      </section>
      <section className="panel"><div className="section-title"><span className="section-number">03</span><h2>Difficulty</h2><button className="text-button" onClick={() => update('difficulties', { 2: 25, 3: 50, 4: 25 })}>Mixed HS preset</button></div><div className="difficulty-options">{DIFFICULTIES.map((d, i) => <label key={d}><span className="eyebrow">LEVEL {d}</span><strong>{['Easy HS', 'Regular HS', 'Hard HS'][i]}</strong><div><input aria-label={`Difficulty ${d} weight`} type="number" min="0" step="any" value={Number.isFinite(c.difficulties[d]) ? c.difficulties[d] : ''} onChange={e => update('difficulties', { ...c.difficulties, [d]: e.target.valueAsNumber })} /><span>{percent(c.difficulties, String(d)).toFixed(1)}%</span></div></label>)}</div></section>
      <section className="panel"><div className="section-title"><span className="section-number">04</span><h2>The reader</h2></div><div className="field-grid"><label>Presentation<select aria-label="Presentation" value={c.presentation} onChange={e => update('presentation', e.target.value as Config['presentation'])}><option value="both">Text + Audio</option><option value="text">Text Only</option><option value="audio">Audio Only</option></select></label><label>Reader engine<select aria-label="Reader engine" value={c.engine} onChange={e => { const engine = e.target.value as Config['engine']; setC(old => ({ ...old, engine, voice: engine === 'system' ? voices[0]?.id ?? '' : 'af_heart' })); }}><option value="auto">Auto · Kokoro, then system</option><option value="kokoro">Kokoro · local neural voice</option><option value="system">System Voice · browser</option></select></label><label>Voice<select aria-label="Voice" value={c.voice} onChange={e => { const voice = e.target.value; setC(old => ({ ...old, voice, engine: voice.startsWith('system:') ? 'system' : old.engine })); }}>{!allVoices.length && <option value="">No local voice installed</option>}{allVoices.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Audio speed · {c.speed.toFixed(2)}×<input type="range" min="0.75" max="1.50" step="0.05" value={c.speed} onChange={e => update('speed', Number(e.target.value))} /></label><label>Text reading speed (WPM)<input type="number" min="60" max="450" value={Number.isFinite(c.wpm) ? c.wpm : ''} onChange={e => update('wpm', e.target.valueAsNumber)} /></label></div><p className="help">Kokoro runs on your device. Its first model download is large and browser-cached. System Voice uses available browser voices; no paid API is required.</p></section>
      <section className="panel"><div className="section-title"><span className="section-number">05</span><h2>Rules & scoring</h2></div><div className="rules-grid">{([['scoring', 'Scoring'], ['powers', 'Powers'], ['interrupts', 'Allow interrupts'], ['negs', 'Incorrect interrupt penalty'], ['resume', 'Resume after incorrect interrupt'], ['rebuzz', 'Allow another buzz after neg']] as const).map(([key, label]) => <Toggle key={key} label={label} value={c[key]} onChange={v => update(key, v)} />)}</div><details><summary>Advanced scoring values</summary><div className="field-grid">{(['power', 'ten', 'neg', 'endWrong', 'bonus'] as const).map((key, i) => <label key={key}>{['Power', 'Regular correct', 'Interrupt penalty', 'Incorrect after end', 'Default bonus part'][i]}<input type="number" value={Number.isFinite(c.scores[key]) ? c.scores[key] : ''} onChange={e => update('scores', { ...c.scores, [key]: e.target.valueAsNumber })} /></label>)}</div><p className="help">An actual bonus part value supplied by QBReader takes precedence over the default.</p></details></section>
      <section className="panel"><div className="section-title"><span className="section-number">06</span><h2>Local preferences</h2></div><Toggle label="Avoid previously seen questions" note="Stable question IDs, saved on this device" value={c.avoidSeen} onChange={v => update('avoidSeen', v)} /><div className="preset-row"><label htmlFor="savedPresets">Saved presets</label><select id="savedPresets" value={selected} onChange={e => { const id = e.target.value; setSelected(id); const loaded = BUILTINS[id] ?? presets.find(p => p.id === id)?.config; if (loaded) setC(structuredClone(loaded)); }}><option value="">Choose a preset</option><optgroup label="Built-in">{Object.keys(BUILTINS).map(name => <option key={name}>{name}</option>)}</optgroup><optgroup label="Your presets">{presets.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</optgroup></select></div><div className="button-row"><button onClick={() => void savePreset()} disabled={!!errors.length}>Save preset</button><button onClick={() => void rename()} disabled={!presets.some(p => p.id === selected)}>Rename</button><button onClick={() => void remove()} disabled={!presets.some(p => p.id === selected)}>Delete preset</button></div><details><summary>Manage local data</summary><div className="button-row"><button onClick={() => { if (window.confirm('Reset all seen question IDs? Session history will remain.')) void db.seen.clear().then(() => setMessage('Question history reset.')); }}>Reset question history</button><button className="danger-text" onClick={() => { if (window.confirm('Permanently delete all settings, quiz bowl sessions, study decks and history, presets, pronunciation corrections, and seen IDs on this device?')) void clearAll().then(() => { setC(structuredClone(DEFAULT_CONFIG)); setPresets([]); onClear(); setMessage('All local data cleared.'); }); }}>Clear all local data</button></div></details>{message && <p role="status">{message}</p>}</section>
    </div><aside className="session-summary"><span className="eyebrow">READY WHEN YOU ARE</span><h2>Your next round</h2><div className="summary-line"><span>Mode</span><strong>{c.mode === 'practice' ? 'Practice' : 'Match'}</strong></div><div className="summary-line"><span>Tossups</span><strong>{c.count || '—'}</strong></div><div className="summary-line"><span>Bonuses</span><strong>{c.bonuses ? 'On' : 'Off'}</strong></div><div className="summary-line"><span>Presentation</span><strong>{c.presentation === 'both' ? 'Text + Audio' : c.presentation === 'audio' ? 'Audio Only' : 'Text Only'}</strong></div><div className="summary-rule" /><p>Questions from QBReader.<br/>Your history stays on this device.</p>{errors.length > 0 && <div className="error-message" role="alert">{errors.map(e => <p key={e}>{e}</p>)}</div>}<button className="primary start-button" disabled={!!errors.length} onClick={() => onStart(c)}>Start session <span>↗</span></button><div className="keyboard-note"><kbd>Space</kbd> buzz <span>·</span> <kbd>Enter</kbd> answer</div><div className="quiet-note">FREE. LOCAL. NO ACCOUNT.</div></aside></div>
  </div>;
}
