import DOMPurify from 'dompurify';
import type { Bonus, Question, Ruling, Tossup } from '../core/types';
export const safeHTML = (html: string) => DOMPurify.sanitize(html, { ALLOWED_TAGS: ['b', 'u', 'i', 'em', 'strong', 'sub', 'sup', 'br'], ALLOWED_ATTR: [] });
export function plainText(html: string): string { const el = document.createElement('div'); el.innerHTML = safeHTML(html).replace(/<br\s*\/?>/gi, ' '); return (el.textContent ?? '').replace(/\s+/g, ' ').trim(); }
function object(x: unknown): Record<string, unknown> { if (!x || typeof x !== 'object' || Array.isArray(x)) throw new Error('Invalid QBReader response.'); return x as Record<string, unknown>; }
function str(x: unknown): string { if (typeof x !== 'string') throw new Error('Missing text in QBReader response.'); return x; }
function num(x: unknown): number { if (typeof x !== 'number' || !Number.isFinite(x)) throw new Error('Invalid numeric field.'); return x; }
function strings(x: unknown): string[] { if (!Array.isArray(x)) throw new Error('Invalid question parts.'); return x.map(str); }
function base(x: Record<string, unknown>): Question { const p = object(x.packet); const s = object(x.set); return { _id: str(x._id), category: str(x.category), subcategory: str(x.subcategory), alternate_subcategory: typeof x.alternate_subcategory === 'string' ? x.alternate_subcategory : undefined, difficulty: num(x.difficulty), number: num(x.number), updatedAt: str(x.updatedAt), packet: { _id: str(p._id), name: str(p.name), number: num(p.number) }, set: { _id: str(s._id), name: str(s.name), year: num(s.year), standard: s.standard === true } }; }
export function parseTossups(data: unknown): Tossup[] { const list = object(data).tossups; if (!Array.isArray(list)) throw new Error('Expected tossups.'); return list.map(item => { const x = object(item); const question = safeHTML(str(x.question)), answer = safeHTML(str(x.answer)); return { ...base(x), question, answer, question_sanitized: plainText(question), answer_sanitized: plainText(answer) }; }); }
export function parseBonuses(data: unknown): Bonus[] { const list = object(data).bonuses; if (!Array.isArray(list)) throw new Error('Expected bonuses.'); return list.map(item => { const x = object(item); const leadin = safeHTML(str(x.leadin)), parts = strings(x.parts).map(safeHTML), answers = strings(x.answers).map(safeHTML); if (!parts.length || answers.length < parts.length) throw new Error('This bonus has missing answerlines.'); const values = Array.isArray(x.values) && x.values.length === parts.length && x.values.every(v => typeof v === 'number' && Number.isFinite(v) && v >= 0) ? x.values as number[] : undefined; return { ...base(x), leadin, parts, answers, leadin_sanitized: plainText(leadin), parts_sanitized: parts.map(plainText), answers_sanitized: answers.map(plainText), values }; }); }
export function parseRuling(data: unknown): Ruling { const x = object(data); if (!['accept', 'reject', 'prompt'].includes(String(x.directive))) throw new Error('Unrecognized answer ruling.'); return { directive: x.directive as Ruling['directive'], directedPrompt: typeof x.directedPrompt === 'string' ? plainText(x.directedPrompt) : null }; }
