import { Component, lazy, Suspense, useCallback, useEffect, useState, type ReactNode } from 'react';
import { DEFAULT_CONFIG } from './core/config';
import type { Config, GameState, Session } from './core/types';
import { db, readSetting, saveSetting, flushWrites } from './data/db';
import { Setup } from './ui/Setup';
import { Game } from './ui/Game';
import { History } from './ui/History';
import { Results } from './ui/Results';
import { Settings } from './ui/Settings';
import { About } from './ui/About';
import { AudioEnableButton } from './ui/AudioEnableButton';
import { unlockReaderAudio } from './reader/audio-gesture';
const Diagnostics = import.meta.env.DEV ? lazy(() => import('./ui/Diagnostics')) : undefined;
const Study = lazy(() => import('./study/ui/StudyHome'));
class ErrorBoundary extends Component<{ children: ReactNode }, { error?: string }> { state: { error?: string } = {}; static getDerivedStateFromError(e: Error) { return { error: e.message }; } render() { return this.state.error ? <main className="panel"><h1>Something interrupted this page.</h1><p>{this.state.error}</p><button onClick={() => window.location.reload()}>Reload saved progress</button></main> : this.props.children; } }
function Cadence() {
  const [view, setView] = useState<'setup' | 'game' | 'history' | 'results' | 'settings' | 'about' | 'diagnostics' | 'study'>('setup'); const [config, setConfig] = useState<Config>(structuredClone(DEFAULT_CONFIG)); const [sessions, setSessions] = useState<Session[]>([]); const [recovery, setRecovery] = useState<GameState>(); const [gameRecovery, setGameRecovery] = useState<GameState>(); const [result, setResult] = useState<Session>(); const [loaded, setLoaded] = useState(false); const [error, setError] = useState(''); const [theme, setTheme] = useState('system');
  const refresh = useCallback(async () => { await flushWrites(); setSessions(await db.sessions.orderBy('createdAt').reverse().toArray()); const r = await readSetting<GameState | null>('recovery'); setRecovery(r || undefined); }, []);
  useEffect(() => { void Promise.all([readSetting<Config>('config'), readSetting<string>('theme'), refresh()]).then(([c, t]) => { if (c) setConfig(c); if (t) setTheme(t); }).catch(() => setError('IndexedDB is unavailable. Allow browser storage to save history and resume sessions.')).finally(() => setLoaded(true)); }, [refresh]);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { const closeDetails = (e: KeyboardEvent) => { if (e.key !== 'Escape') return; const focused = document.activeElement?.closest('details[open]'); document.querySelectorAll('details[open]').forEach(d => d.removeAttribute('open')); if (focused) (focused.querySelector('summary') as HTMLElement | null)?.focus(); }; window.addEventListener('keydown', closeDetails); return () => window.removeEventListener('keydown', closeDetails); }, []);
  const newSession = () => { setView('setup'); void refresh(); };
  const start = (c: Config) => { if (c.presentation !== "text") void unlockReaderAudio(); if (recovery && !window.confirm('A saved session is in progress. Start a new session and replace its recovery checkpoint? Its saved attempts will remain in History.')) return; setConfig(structuredClone(c)); setGameRecovery(undefined); setView('game'); };
  const resume = () => { if (!recovery) return; if (recovery.session.config.presentation !== "text") void unlockReaderAudio(); const r = structuredClone(recovery); if (r.phase === 'CHECKING') r.phase = 'BUZZED'; if (r.phase === 'BONUS_CHECKING') r.phase = 'BONUS_PART'; setConfig(r.session.config); setGameRecovery(r); setView('game'); };
  const complete = useCallback((s: Session) => { setResult(s); setView('results'); setRecovery(undefined); void flushWrites().then(() => db.sessions.put(s)).then(() => saveSetting('recovery', null)).then(refresh).catch(() => setError('Could not save the completed session. Keep this page open.')); }, [refresh]);
  return <><header className="app-header"><a href="#" className="brand" onClick={e => { e.preventDefault(); if (view !== 'game') newSession(); }}><span className="brand-mark" aria-hidden="true">c.</span><strong>cadence<span>QUIZ BOWL PRACTICE</span></strong></a><nav aria-label="Main navigation"><button className={view === 'setup' || view === 'game' ? 'active' : ''} disabled={view === 'game'} onClick={newSession}>Practice room</button><button disabled={view === 'game'} className={view === 'study' ? 'active' : ''} onClick={() => setView('study')}>Study</button><button className={view === 'history' ? 'active' : ''} disabled={view === 'game'} onClick={() => { void refresh(); setView('history'); }}>History & stats</button><button disabled={view === 'game'} className={view === 'settings' ? 'active' : ''} onClick={() => setView('settings')}>Settings</button><button disabled={view === 'game'} className={view === 'about' ? 'active' : ''} onClick={() => setView('about')}>About</button>{Diagnostics && <button disabled={view === 'game'} onClick={() => setView('diagnostics')}>Diagnostics</button>}</nav><button className="theme-button" aria-label="Toggle theme" onClick={() => { const dark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches); const next = dark ? 'light' : 'dark'; setTheme(next); void saveSetting('theme', next); }}>◐</button></header>
    <main><AudioEnableButton/>{error && <p className="error-message" role="alert">{error}</p>}{!loaded ? <div className="loading-state">Opening your practice room…</div> : view === 'setup' ? <>{recovery && <div className="recovery-banner"><span>Pick up where you left off · {recovery.session.config.mode} · Tossup {recovery.number}/{recovery.session.config.count}</span><button onClick={resume}>Resume session →</button></div>}<Setup initial={config} onChange={setConfig} onStart={start} onClear={() => { setSessions([]); setRecovery(undefined); }}/></> : view === 'game' ? <Game config={config} recovery={gameRecovery} onComplete={complete} onExit={newSession}/> : view === 'study' ? <Suspense fallback={<p>Opening your clue library…</p>}><Study/></Suspense> : view === 'history' ? <History sessions={sessions} onOpen={s => { setResult(s); setView('results'); }} onDelete={async id => { await db.sessions.delete(id); if (recovery?.session.id === id) { await saveSetting('recovery', null); setRecovery(undefined); } await refresh(); }} onNew={newSession}/> : view === 'settings' ? <Settings config={config} onImported={async () => { await refresh(); const c = await readSetting<Config>('config'); const t = await readSetting<string>('theme'); if (c) setConfig(c); if (t) setTheme(t); }}/> : view === 'about' ? <About/> : view === 'diagnostics' && Diagnostics ? <Suspense fallback={<p>Opening diagnostics…</p>}><Diagnostics config={config}/></Suspense> : result ? <Results sessions={[result]} single onNew={newSession}/> : null}</main>
    <footer className="app-footer"><span>Made for the next clue.</span><span>Free & local <span>·</span> Questions by <a href="https://www.qbreader.org" target="_blank" rel="noreferrer">QBReader ↗</a></span></footer></>;
}
export default function App() { return <ErrorBoundary><Cadence/></ErrorBoundary>; }
