import { useState } from 'react';
import { editCard } from '../storage';
import type { Flashcard } from '../types';

export function CardEditor({ card, onSaved, onCancel }: { card: Flashcard; onSaved(): void; onCancel(): void }) {
  const [value, setValue] = useState(card), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  return <form className="study-editor" aria-label={`Edit ${card.answer}`} onSubmit={e => { e.preventDefault(); setBusy(true); void editCard(value).then(onSaved).catch(e => setError(String(e))).finally(() => setBusy(false)); }}><h3>Edit card</h3><div className="field-grid"><label className="study-field">Answer<input required value={value.answer} onChange={e => setValue({ ...value, answer: e.target.value })}/></label><label className="study-field">Answer type<input required value={value.answerType} onChange={e => setValue({ ...value, answerType: e.target.value })}/></label><label className="study-field">Category<input value={value.category} onChange={e => setValue({ ...value, category: e.target.value })}/></label><label className="study-field">Subcategory<input value={value.subcategory} onChange={e => setValue({ ...value, subcategory: e.target.value })}/></label></div><label className="study-field">Clue text<textarea aria-label="Clue text" rows={4} required value={value.clueText} onChange={e => setValue({ ...value, clueText: e.target.value })}/></label><label className="study-field">Aliases (one per line)<textarea aria-label="Aliases (one per line)" rows={3} value={value.aliases.join('\n')} onChange={e => setValue({ ...value, aliases: e.target.value.split('\n').map(s => s.trim()).filter(Boolean) })}/></label><p className="help">The answer-type prefix updates when you save. Editing preserves this card’s historical statistics.</p>{error && <p role="alert" className="error-message">{error}</p>}<div className="button-row"><button className="primary" disabled={busy}>Save card</button><button type="button" disabled={busy} onClick={onCancel}>Cancel edit</button></div></form>;
}
const STATUS = { pending: 'Not analyzed', ready: 'Ready', insufficient: 'Insufficient Data', 'no-matches': 'No matching questions', error: 'Analysis failed' };
export function CardReview({ cards, busy, onChanged, onRemove, onRegenerate }: { cards: Flashcard[]; busy: boolean; onChanged(): void; onRemove(card: Flashcard): void; onRegenerate(card: Flashcard): void }) {
  const [page, setPage] = useState(0), [editor, setEditor] = useState<string>(), [filter, setFilter] = useState('all');
  const filtered = cards.filter(c => filter === 'all' || c.generationStatus !== 'ready' || !!c.error);
  const pages = Math.max(1, Math.ceil(filtered.length / 20)), current = Math.min(page, pages - 1);
  return <section className="panel"><div className="section-title"><h2>Review cards</h2><label>Show<select aria-label="Review filter" value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}><option value="all">All cards ({cards.length})</option><option value="attention">Needs attention</option></select></label></div><p className="help">You can save in bulk. Cards with ten or fewer useful direct sources, or fewer than five clue concepts, remain flagged for your judgment.</p>{filtered.slice(current * 20, current * 20 + 20).map(card => <article className="study-review-card" key={card.id}><div className="study-row"><h3>{card.answer}</h3><span className={`study-status ${card.generationStatus === 'ready' ? '' : 'attention'}`}>{STATUS[card.generationStatus]}</span></div><small>{card.sourceCount} relevant questions/items · {card.hardClues.length + card.commonClues.length} clues selected · {card.category}{card.subcategory ? ` / ${card.subcategory}` : ''}</small><p className="study-clue-preview">{card.clueText || 'No supported clue text yet. Retry analysis, edit this card, or remove it.'}</p>{card.error && <p className="error-message" role="alert">{card.error}</p>}<div className="button-row"><button disabled={busy} onClick={() => setEditor(card.id)}>Edit</button><button disabled={busy} onClick={() => onRegenerate(card)}>Regenerate clue</button><button disabled={busy} onClick={() => onRemove(card)}>Remove</button></div><details><summary>Sources & generation evidence</summary><p className="help">Frequency counts refer to distinct source items, not repeated words within one question. Hard clues use power markers or an initial bold power span. Related bonus parts enrich clues but do not count toward the minimum data threshold.</p>{[...card.hardClues, ...card.commonClues].map((c, i) => <p className="help" key={i}>{c.text} · {c.pool} · {c.frequency} sources · {c.powerFrequency} in power</p>)}<div className="study-sources">{card.sources.map(source => <details key={source.id}><summary>{source.kind}{source.part !== undefined ? ` part ${source.part + 1}` : ''} · {source.setName} / {source.packetName}{source.related ? ' · related' : ''}</summary><small>QBReader ID: {source.questionId} · Difficulty {source.difficulty}</small><p>{source.text.replace(/<[^>]*>/g, '')}</p><p>Answerline: {source.answerline.replace(/<[^>]*>/g, '')}</p></details>)}</div></details>{editor === card.id && <CardEditor key={card.id} card={card} onSaved={() => { setEditor(undefined); onChanged(); }} onCancel={() => setEditor(undefined)}/>}</article>)}{!filtered.length && <p>No cards need attention.</p>}<div className="review-pagination"><button disabled={current === 0} onClick={() => setPage(current - 1)}>Previous cards</button><span>{current + 1} / {pages}</span><button disabled={current + 1 >= pages} onClick={() => setPage(current + 1)}>Next cards</button></div></section>;
}
