import { useState } from 'react';
import { randomCards, selectSets, splitSets } from '../practice';
import type { Deck, Flashcard, PracticeSpec, StudyFilters } from '../types';
export function SetPicker({ deck, cards, onPractice }: { deck: Deck; cards: Flashcard[]; onPractice(spec: PracticeSpec): void }) {
  const sets = splitSets(cards, deck.setSize), [first, setFirst] = useState(1), [last, setLast] = useState(1);
  const spec = (start: number, end: number): PracticeSpec => ({ label: `${deck.name} · ${start === end ? `Set ${start}` : `Sets ${start}–${end}`}`, deckId: deck.id, cards: selectSets(cards, deck.setSize, start, end) });
  const begin = (start: number, end: number) => { const run = spec(start, end); if (end < sets.length) run.next = spec(end + 1, end + 1); onPractice(run); };
  return <section className="panel"><h2>Practice sets</h2><p className="help">{cards.length} usable cards · {sets.length} sets · {deck.setSize} per set. Insufficient-data cards with clue text are included; remove any you do not trust in review.</p><div className="study-set-grid">{sets.map((set, i) => <button key={i} onClick={() => begin(i + 1, i + 1)}>Set {i + 1}<small>{set.length} cards</small></button>)}</div>{sets.length > 0 && <><div className="study-import-row"><label>From set<input aria-label="From set" type="number" min={1} max={sets.length} value={first} onChange={e => setFirst(Number(e.target.value))}/></label><label>Through set<input aria-label="Through set" type="number" min={first} max={sets.length} value={last} onChange={e => setLast(Number(e.target.value))}/></label><button disabled={!selectSets(cards, deck.setSize, first, last).length} onClick={() => begin(first, last)}>Practice range</button><button onClick={() => begin(1, sets.length)}>All Sets</button></div><div className="button-row">{[2, 5, 10].filter(n => n <= sets.length).map(n => <button key={n} onClick={() => begin(1, n)}>Sets 1–{n}</button>)}</div></>}</section>;
}
export function RandomPractice({ cards, decks, onPractice }: { cards: Flashcard[]; decks: Deck[]; onPractice(spec: PracticeSpec): void }) {
  const [count, setCount] = useState(20), [filters, setFilters] = useState<StudyFilters>({});
  const eligible = randomCards(cards, cards.length, filters);
  const field = (key: 'category' | 'subcategory' | 'answerType', label: string) => <label className="study-field">{label}<select aria-label={label} value={filters[key] || ''} onChange={e => setFilters({ ...filters, [key]: e.target.value })}><option value="">All</option>{[...new Set(cards.map(c => c[key]).filter(Boolean))].sort().map(value => <option key={value}>{value}</option>)}</select></label>;
  return <section className="panel"><h2>Random library practice</h2><p className="help">Draw across saved decks, without repeated answer targets. If fewer cards match, practice all available matches.</p><div className="field-grid"><label className="study-field">Cards<select aria-label="Random card count" value={count} onChange={e => setCount(Number(e.target.value))}>{[20, 50, 100].map(n => <option key={n}>{n}</option>)}</select></label><label className="study-field">Deck<select value={filters.deckId || ''} onChange={e => setFilters({ ...filters, deckId: e.target.value })}><option value="">All decks</option>{decks.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{field('category', 'Category')}{field('subcategory', 'Subcategory')}{field('answerType', 'Answer type')}</div><p><small>{eligible.length} unique matching cards</small></p><button className="primary" disabled={!eligible.length} onClick={() => onPractice({ label: `Random ${filters.category || 'library'} practice`, cards: randomCards(cards, count, filters), random: { count, filters } })}>Start random practice</button></section>;
}
