import { useState } from 'react';
import { groupedStudyMetrics, studyMetrics } from '../statistics';
import type { CardAttempt, Deck, StudySession } from '../types';
export function StudyStats({ attempts, decks, sessions }: { attempts: CardAttempt[]; decks: Deck[]; sessions: StudySession[] }) {
  const [group, setGroup] = useState<'category' | 'subcategory' | 'answerType' | 'deckId' | 'cardId' | 'sessionId'>('category');
  const total = studyMetrics(attempts);
  const label = (key: string) => group === 'deckId' ? decks.find(d => d.id === key)?.name || 'Deleted deck' : group === 'cardId' ? attempts.find(a => a.cardId === key)?.answer || key : group === 'sessionId' ? sessions.find(s => s.id === key)?.label || key : key;
  return <section className="panel"><h2>Study statistics</h2><div className="metric-strip"><div className="metric"><span>APPEARANCES</span><strong>{total.appearances}</strong></div><div className="metric"><span>FIRST-TRY ACCURACY</span><strong>{total.firstAccuracy.toFixed(0)}%</strong></div><div className="metric"><span>LIFETIME SUBMISSION ACCURACY</span><strong>{total.lifetimeAccuracy.toFixed(0)}%</strong></div><div className="metric"><span>TOTAL ATTEMPTS</span><strong>{total.attempts}</strong></div></div><label>Group by<select aria-label="Study statistics group" value={group} onChange={e => setGroup(e.target.value as typeof group)}><option value="category">Category</option><option value="subcategory">Subcategory</option><option value="answerType">Answer type</option><option value="deckId">Deck</option><option value="cardId">Card</option><option value="sessionId">Session</option></select></label><div className="table-scroll"><table><thead><tr><th>Group</th><th>Appearances</th><th>First try</th><th>Second try</th><th>Third+</th><th>Attempts</th><th>First-try accuracy</th><th>Lifetime accuracy</th><th>Trouble runs</th><th>Last practiced</th></tr></thead><tbody>{groupedStudyMetrics(attempts, group).map(row => <tr key={row.key}><td>{label(row.key)}</td><td>{row.appearances}</td><td>{row.first}</td><td>{row.second}</td><td>{row.third}</td><td>{row.attempts}</td><td>{row.firstAccuracy.toFixed(0)}%</td><td>{row.lifetimeAccuracy.toFixed(0)}%</td><td>{row.trouble}</td><td>{row.lastPracticed ? new Date(row.lastPracticed).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></div>{!attempts.length && <p className="help">Complete a study card to start your history.</p>}<p className="help">First-try accuracy uses appearances with a submission, including unfinished cards. Lifetime accuracy is correct submissions divided by all submissions.</p></section>;
}
